config/routes.rb
PaypalDemo::Application.routes.draw do  # The priority is based upon order of creation:

  resources :products do 
    collection do
      post 'notification'
    end
  end
   

  root :to => 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders

  def paypal_url(return_url, notify_url)
    values = {
      :business => AppConfig.paypal_email,
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :notify_url => notify_url,
      :cert_id => AppConfig.cert_id,
      :invoice => rand(10000)
    }
    values.merge!({
      "amount_1" => unit_price,
      "item_name_1" => name,
      "item_number_1" => id,
      "quantity_1" => '1'
    })
    encrypt_for_paypal(values)
  end

  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/#{Rails.env}/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/#{Rails.env}/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/#{Rails.env}/app_key.pem")

  # openssl encryption.
  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    flash[:notice] = "Your Transaction is #{params[:st]} for Amount of $#{params[:amt]}. Thank You for shopping." if params[:st]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  def notification
    #handle for old deals.
    if params[:item_number1] && !params[:item_number1].empty?
      #paypal sends an IPN even when the transaction is voided.
      if params[:payment_status] != 'Voided'
        @product = Product.find(params[:item_number1].to_i) rescue nil
        @product.orders.build(:quantity => 1, :amount => params[:mc_gross_1], :status => params[:payment_status]).save unless @product.nil?
      end
    end
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <% flash.each do |key, message| %>
    <div class="span16">
      <div class="alert-message <%= key %>" data-alert><a class="close" href="#">×</a><p><%= message %></p></div>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="topbar" data-scrollspy="scrollspy">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">My Site</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Site</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js",
                             "http://twitter.github.com/bootstrap/1.4.0/bootstrap-scrollspy.js",
                             "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= render 'layouts/flash', :flash => flash %>
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class=''>
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :unit_price %><br />
	    <%= f.text_field :unit_price %>
	  </div>
	  <div class="actions">
	    <%= f.submit :class => "btn primary" %>
	  </div>
  </div>
<% end %>

app/views/products/_paypal.html.erb
<%= form_tag AppConfig.paypal_url do %>
	<%= hidden_field_tag :cmd, "_s-xclick" %>
	<%= hidden_field_tag :encrypted, product.paypal_url(products_url, notification_products_url) %>
	<p><%= submit_tag "Buy Now!!", :class => "btn primary"%></p>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Unit price</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.unit_price %></td>
	<td><%= render :partial => 'paypal', :locals => { :product => product } %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Unit price:</b>
  <%= @product.unit_price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>